- name: Set up EC2 instance
  hosts: localhost
  connection: local
  roles:
    - drone-aws

- name: Deploy drone
  hosts: drone-group
  remote_user: ec2-user
  become: yes
  gather_facts: no
  roles:
    - install-docker
    - setup-drone
